name: cross_platform_sdk_flutter_plugin
description: A Flutter plugin that bridges to native code for detecting installed UPI apps.
version: 0.0.1
homepage: https://github.com/your-org/flutter_plugin
repository: https://github.com/your-org/flutter_plugin
issue_tracker: https://github.com/your-org/flutter_plugin/issues
license: MIT
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.crossplatform.flutter_plugin
        pluginClass: FlutterPlugin
      ios:
        pluginClass: FlutterPlugin
